# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-Image-Cut
version:      0.06
version_from: lib/Tk/Image/Cut.pm
installdirs:  site
requires:
    Tk:                            804.027
    Tk::FileSelect:                4.015
    Tk::Frame:                     0
    Tk::Image::Calculation:        0
    Tk::JPEG:                      0
    Tk::PNG:                       4.003

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
