# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-Image-Cut
version:      0.04
version_from: lib/Tk/Image/Cut.pm
installdirs:  site
requires:
    Tk:                            Tk::Frame
    Tk::FileSelect:                Tk::JPEG
    Tk::PNG:                       Tk::Image::Calculation

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
